### ISSUE TITLE
Feature request: Support for Promise.allSettled()

### ISSUE THREAD

**Issue by tobinus** [marcelowa/promise-all-properties#16]
Hi! Would support for [`Promise.allSettled()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) be an acceptable increase in scope for this package? It is a useful alternative to `Promise.all` when you want to work with _all_ rejected promises, and not just the first one.

I'm considering implementing this myself and contributing it as a pull request, but I don't want to go ahead before knowing if this is okay. Implementation-wise there won't be much of a difference between wrapping `Promise.allSettled()` and `Promise.all()`, since they both take an iterable of promises or values and return an array with the results in the same order, though the types would need to be different.

**Comment by marcelowa** [comment]
@tobinus sounds great, go ahead and open a PR, I'll be happy to add this feature
Please consider the following when implementing your change
- Backward compatibility  / breaking changes - the existing tests should support you there
- Relevant tests for the new features
- Add the relevant documentation to the Readme file
Thanks.

**Comment by tobinus** [comment]
@marcelowa Thanks for the reply! I'll give it a try.
